# Generated by Django 5.1.6 on 2025-02-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_image', models.URLField(default='https://i.pinimg.com/1200x/e2/ae/e5/e2aee59c58c648664bb1dfa3b2ea1453.jpg')),
            ],
        ),
    ]
